import type { Metadata } from "next";

import { IBM_Plex_Sans } from "next/font/google";

import "./globals.css";

const ibmPlexSans = IBM_Plex_Sans({
	display: "swap",
	subsets: ["latin"],
	weight: ["500", "600", "700"],
	variable: "--font-ibmPlexSans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${ibmPlexSans.variable} `}>{children}</body>
		</html>
	);
}
